### ISSUE TITLE
Create i postman kunde inte lägga till

### ISSUE THREAD

**Issue by ss223ck** [fh222dt/fh222dt_ror#10]
Create i postman kunde inte lägga till en plats. Fick bad request och "Kunde inte lägga till platsen, stämmer parametrarna?"

**Comment by fh222dt** [comment]
Ja det var inte konstigt då jag glömt att uppdatera postman-filen med korrekta parametrar. "city" ska heta "address". Jag har uppdaterat [postmanfilen](fh222dt_ror/PicknickAPI.json.postman_collection) som finns i repot. Ursäkta min slarvighet :(
