### ISSUE TITLE
gem 'tzinfo-data'

### ISSUE THREAD

**Issue by mi222ep** [fh222dt/fh222dt_ror#6]
När jag skulle befolka databasen fick jag först ett fel "TZInfo::DataSourceNotFound: No source of timezone data could be found."
När jag lade till gem tzinfo-data på gemlistan fungerade allt som det skulle. Jag vet ej om det var ett lokalt fel hos mig, men kändes ändå värt att nämna

**Comment by fh222dt** [comment]
Detta verkar vara något som uppstår om man kör ror på windows [https://github.com/tzinfo/tzinfo/wiki/Resolving-TZInfo::DataSourceNotFound-Errors](https://github.com/tzinfo/tzinfo/wiki/Resolving-TZInfo::DataSourceNotFound-Errors)

Jag lägger till gemet eftersom det löser problemet
