### ISSUE TITLE
Kan inte köra bundle install

### ISSUE THREAD

**Issue by ss223ck** [fh222dt/fh222dt_ror#7]
Får detta felmeddelande C:\Users\User\Documents\GitHub\fh222dt_ror-2.0>bundle install
DL is deprecated, please use Fiddle
Fetching gem metadata from https://rubygems.org/...........
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies...
Could not find jwt-1.5.3 in any of the sources

och

C:\Users\User\Documents\GitHub\fh222dt_ror-2.0>rake db:setup
Could not find rails-html-sanitizer-1.0.2 in any of the sources
Run `bundle install` to install missing gems.

**Comment by fh222dt** [comment]
Hej! Ditt första fel DL is `deprecated, please use Fiddle` verkar vara mer av en varning på windows: [http://stackoverflow.com/questions/15590450/ruby-2-0-0p0-irb-warning-dl-is-deprecated-please-use-fiddle](http://stackoverflow.com/questions/15590450/ruby-2-0-0p0-irb-warning-dl-is-deprecated-please-use-fiddle)

`Could not find jwt-1.5.3 in any of the sources` beror tydligen på att den versionen inte finns i repot den ska hämtas från. [http://stackoverflow.com/questions/36216967/rails-installed-gem-version-and-gemfile-lock-version](http://stackoverflow.com/questions/36216967/rails-installed-gem-version-and-gemfile-lock-version). Jag testade lösningen med att ta bort `gemfile.lock` och det verkar funka. Kanske kan du testa det. Det borde göra att gemsen kan installeras som det är tänkt. 

Jag har bara kört min applikation på cloud 9, så det kanske kan vara orsaken till problemet?

Hör gärna av dig igen annars
/Frida

**Comment by ss223ck** [comment]
Det fungerade efter att jag tog bort gemfile.lock
