### ISSUE TITLE
Getförfrågan på "places"

### ISSUE THREAD

**Issue by ss223ck** [fh222dt/fh222dt_ror#8]
Jag skulle inte skicka med "tags" som är kopplade till "places" vid vanliga getförfrågningar av "places". Det kommer bara belasta nätverket onödigt mycket. Vill man få ut "places" så ska man få ut "places" med en request. Vill man veta vilka "tags" som är kopplade till olika platser skickar man en ny request. Möjligtvis skulle man kunna skicka med en parameter i förfrågan om man vill ha med "tags" när man ska få ut "places".

**Comment by fh222dt** [comment]
Det har du nog rätt i, gillar förslaget med att ha det som en parameter istället
