### ISSUE TITLE
Update places

### ISSUE THREAD

**Issue by ss223ck** [fh222dt/fh222dt_ror#9]
Jag försöker köra update places som fanns i postman-filen. Men lyckas inte få någon feedback alls från api:et. Inte ens när jag anger en felaktig api-nyckel.

**Comment by ss223ck** [comment]
Parametrarna borde också ligga i body:n vid förfrågningarna

**Comment by ss223ck** [comment]
Såg nu att servern skrev 401 i consolen

**Comment by fh222dt** [comment]
Som jag har skrivit i min [dokumentation](https://github.com/fh222dt/fh222dt_ror#dokumentation-api) för apiet:

> Jag föreslår att du börjar med att köra "Authenticate your self" från postman-filen. Då får du en JWT-web token tillbaka. Den används sedan i form av en Authorization headers när du ska göra något av ovan nämnda.

Har man inte gjort detta så får man 401 tillbaka. Jag bör kanske vara tydligare i själva apiet dock med ett felmeddelande kring detta
